name: drenfw
description: "drendrendren basic framework"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path_ios: "assets/images/app_logo.jpg"
  image_path_android: "assets/images/app_logo.jpg"
  remote_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/appbar_logo.png